### ISSUE TITLE
client.query method, $[num], can not be used in LIKE statement

### ISSUE THREAD

**Issue by EasyFrankie** [numtel/meteor-pg#14]
Hey man, great package. 

```
SQL = "SELECT * FROM goods WHERE  goods.name ILIKE '%$1%' "
//Code
pg.connect(CONN_STR, function(error, client, done){
        client.query(SQL, ['car'], function(error, result){
```

I got the error:

> error: bind message supplies 1 parameters, but prepared statement "" requires 0
> arguments: undefined
> code: "08P01"
> column: undefined
> constraint: undefined
> dataType: undefined
> detail: undefined
> file: "postgres.c"
> hint: undefined
> internalPosition: undefined
> internalQuery: undefined
> length: 130
> line: "1527"
> message: "bind message supplies 1 parameters, but prepared statement "" requires 0"
> name: "error"
> position: undefined
> routine: "exec_bind_message"
> schema: undefined
> severity: "ERROR"
> stack: undefined
> table: undefined
> type: undefined
> where: undefined
> **proto**: Error

Seems like $[num] cannot be used in ' ', how should I do if I want to use $[num] to pass parameter to LIKE statement? I cannot find any relevant docs, thanks.

**Comment by numtel** [comment]
I would think that you would need to put the percent characters inside the query parameter value.

```
SQL = "SELECT * FROM goods WHERE  goods.name ILIKE $1"
//Code
pg.connect(CONN_STR, function(error, client, done){
        client.query(SQL, ['%car%'], function(error, result){
```

**Comment by EasyFrankie** [comment]
That's a wonderful idea,  thx man, it works, cheers!
