### ISSUE TITLE
SubBuffer in registerStore not always defined

### ISSUE THREAD

**Issue by waeltken** [numtel/meteor-pg#6]
[This line](https://github.com/numtel/meteor-pg/blob/master/lib/PgSubscription.js#L67) throws exceptions.

If you rapidly change a `PgSubscription` via the `change`-method, you end up with some exceptions because `subBuffer` may sometimes be `undefined`.
I think a simple check for `undefined` should solve the issue.

**Comment by numtel** [comment]
Please make a pull request with a test for this feature and I will release
a new version.

**Comment by waeltken** [comment]
Thanks for your the reply.

I am not quite sure on how to write the test for that. I've not used tinytest yet. Found your blog post though.
What i would want to do is:

1. Subscribe to a publication
2. That publication should be artificially slow (in my real world use-case it is a little slow).
3. While we are still waiting for the initial response for the publication we change the subscription via the change method.
4. When the initial response arrives and we already changed that subscription it is no longer found hence the subBuffer is undefined.

I am currently using your meteor-pg library in combination with the postgis extension to postgres to display geoinformation on a map and do geospacial queries. It's imho the best of the available postgres packages in the meteor world. Will probably release my code for that in the near future, so would be really good to learn how to write those tests for packages. Currently i use the xolvio:cucumber package for end-to-end testing with velocity, not tinytest though.

**Comment by waeltken** [comment]
I'll see if i can update the pull request soon. Thx for the feedback.

**Comment by numtel** [comment]
Just released version 1.0.1 incorporates your test and uses your same technique of exiting early from the `registerStore` `update` method. Thank you for the help!

**Comment by waeltken** [comment]
Thanks, Mr. Green. ;-)
