### ISSUE TITLE
Parameterize PgSubscription

### ISSUE THREAD

**Issue by Joe32** [numtel/meteor-pg#9]
Thanks for this lib works pretty nice. Is it possible to parameterize sql query? If I can understand docs correctly the method PgSubscription.change([args...]) should be able to do that? 
But I can't get it to work(and there is no example of change in leaderboards). 
So far I am using method described here:http://stackoverflow.com/questions/31100338/how-to-show-data-from-postgres-in-meteor/31113676#31113676

**Comment by numtel** [comment]
You only need to use the change method if you want to change the Murray's parameters after initialization. 

See the test case: https://github.com/numtel/meteor-pg/blob/master/test/PgSubscription.js#L260

The arguments to the Meteor.publish function can be used just like with a Mongo  query.

**Comment by Joe32** [comment]
OK my bad I wrote new app from scratch and it's working, awesome! Btw Murray's parameters who is Murray?

**Comment by numtel** [comment]
hah whoops, that was my phone autocorrecting "query's". Very cool you got it working.
